### ISSUE TITLE
All alerts have buttons - how do you remove the button?

### ISSUE THREAD

**Issue by thedoglett** [softon/sweetalert#9]
This is working fine on Laravel but no matter what I do, there is always a button on the alert.

I wanted a simple 'Success!' modal with icon to flash up on the screen and then autoclose in a couple of seconds. I thought using 'false' would work…

`
swal()->button(false)->info('Good Job','You have successfully logged In!'); `

…but it doesn't. The button just says 'false' instead.

What parameter do I need to pass to remove the button from the modal?

_P.S. I see in the config file that you can choose to show/hide the confirm and cancel buttons, but ideally would like to pass the option to do this via the swal() code._

Many thanks.

**Comment by softon** [comment]
In the config `sweetalert.php` set the `showConfirmButton = false`. Check Sweetalert2 documentation for other configs.

**Comment by thedoglett** [comment]
Hi, apologies for the delay in getting back to you.

Yes that's what I did, as I mentioned in my original question, but I don't want ot hide it globally - only on certain modals.

Obviously I can create modals using jQuery and determine if I want a button or not, but from the controller - unfortunately - the way indicated above is an all or nothing, system-wide approach.

So, what I'm asking is if there's some way to show/hide a confirm button when swal() is sent from the controller?

Many thanks.
